# config.yml —— 所有配置集中于此
uuid: "00b8b05a-bced-4c45-9a92-b416a7edecd7"                       #输入uuid
tuic_port: "8361"                  #输入端口=确认部署
hy2_port: "8361"                   #输入端口=确认部署
reality_port: ""               #输入端口=确认部署
sni: "www.bing.com"
